# Numpy 특징
- Numerical Python의 약자
- 고성능 과학 계산용 패키지로 N차원 배열 객체
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
- 정교한 브로드캐스팅 기능
- 파이썬의 list와 비슷하지만 더 빠르고 효율적인 메모리 관리
- 반복문 없이 데이터 배열에 대한 처리

In [1]:
import numpy as np
np.__version__

'1.19.2'

In [4]:
a1 = np.array([1,2,3,4,5]) # 1차원 배열
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])

a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]


In [6]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
1 5 9


In [7]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(type(a3))
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(3, 3, 3)


# 배열 생성 및 초기화

- zeros() : 모든 요소를 0으로 초기화

In [9]:
np.zeros(10) #10개의 요소를 0으로 만듦

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones() : 모든 요소를 1로 초기화

In [10]:
np.ones((3,3)) #3열 3행의 2차원 배열의 요소를 1로 만듦

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full() : 모든 요소를 지정한 값으로 초기화

In [12]:
np.full((3,3), 5) #3열 3행의 2차원 배열의 요소를 5로 만듦

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- eye() : 단위행렬(identity matrix) 생성
    - 주대각선의 원소가 모두 1이고 나머지는 0인 정사각 행렬

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- tri() : 삼각행렬 생성

In [17]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty() : 초기화되지 않은 배열 생성

In [18]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like() : 지정된 배열과 shape이 같은 행렬 생성
    - np.zeros_like()
    - np.ones_like()
    - np.full_like()
    -np.empty_like()

In [19]:
print(a1)
np.zeros_like(a1)

[4 2 3 4 5]


array([0, 0, 0, 0, 0])

In [20]:
print(a1)
np.ones_like(a2)

[4 2 3 4 5]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

# 생성한 값으로 배열 생성

- arange() : 정수범위로 배열 생성

In [23]:
np.arange(0, 30, 2) # 0부터 30까지 2스텝으로

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace() : 범위 내에서 균등 간격의 배열 생성

In [24]:
np.linspace(0, 1, 5) # 0부터 1까지 균등하게 5로 나눔

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() : 범위 내에서 균등 간격으로 로그 스케일 배열 생성

In [25]:
np.logspace(0.1 ,1 , 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

# 표준 데이터 타입

In [30]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
np.full((3,3), 1, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 배열 조회

In [38]:
def array_info(array) :
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:", array.size)
    print("itemsize:", array.itemsize)
    print("nbytes:" , array.nbytes)
    print("strides:" , array.strides)

In [40]:
print(array_info(a1))
print(array_info(a2))
print(array_info(a3))

[4 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)
None
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)
None
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)
None


# 인덱싱(Indexing)

In [41]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [42]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, -1])
print(a2[-2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
6
5


In [43]:
print(a3)
print(a3[0, 0, 0])
print(a3[2, 1, 2])
print(a3[-1, 2, 1])
print(a3[1, 0, -2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
6
8
2


# 슬라이싱(Slicing)

In [44]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [47]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# 불리언 인덱싱(Boolean Indexing
- 배열 각 요소의 선택 여부를 True, False로 지정
- True 값인 인덱스만 조회

In [48]:
print(a1)
bool = [False, True, True, False, False]
print(a1[bool])

[4 2 3 4 5]
[2 3]


# 팬시 인덱싱(Fancy Indexing)

In [55]:
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])
idx = np.array([[0,1], [2,0]])
print(a1[idx])

[4 2 3 4 5]
[4, 3]
[4 3]
[[4 2]
 [3 4]]


In [56]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


# 배열 전치 및 축 변경

In [57]:
print(a2)
print(a2.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


# 배열 재 구조화

- reshape() : 배열의 형상을 변경

In [59]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
