# Numpy 특징
- Numerical Python의 약자
- 고성능 과학 계산용 패키지로 N차원 배열 객체
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
- 정교한 브로드캐스팅 기능
- 파이썬의 list와 비슷하지만 더 빠르고 효율적인 메모리 관리
- 반복문 없이 데이터 배열에 대한 처리

In [2]:
import numpy as np
np.__version__

'1.19.2'

In [10]:
a1 = np.array([1,2,3,4,5]) # 1차원 배열
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])

a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 2 3 4 5]


In [11]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0,0], a2[1,1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
1 5 9


In [12]:
a3 = np.array([ [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ],
                [ [1,2,3], [4,5,6], [7,8,9] ] ])
print(a3)
print(type(a3))
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(3, 3, 3)


# 배열 생성 및 초기화

- zeros() : 모든 요소를 0으로 초기화

In [13]:
np.zeros(10) #10개의 요소를 0으로 만듦

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- ones() : 모든 요소를 1로 초기화

In [14]:
np.ones((3,3)) #3열 3행의 2차원 배열의 요소를 1로 만듦

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full() : 모든 요소를 지정한 값으로 초기화

In [15]:
np.full((3,3), 5) #3열 3행의 2차원 배열의 요소를 5로 만듦

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- eye() : 단위행렬(identity matrix) 생성
    - 주대각선의 원소가 모두 1이고 나머지는 0인 정사각 행렬

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- tri() : 삼각행렬 생성

In [17]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

- empty() : 초기화되지 않은 배열 생성

In [18]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- _like() : 지정된 배열과 shape이 같은 행렬 생성
    - np.zeros_like()
    - np.ones_like()
    - np.full_like()
    -np.empty_like()

In [19]:
print(a1)
np.zeros_like(a1)

[4 2 3 4 5]


array([0, 0, 0, 0, 0])

In [20]:
print(a1)
np.ones_like(a2)

[4 2 3 4 5]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

# 생성한 값으로 배열 생성

- arange() : 정수범위로 배열 생성

In [22]:
np.arange(0, 30, 2) # 0부터 30까지 2스텝으로

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace() : 범위 내에서 균등 간격의 배열 생성

In [23]:
np.linspace(0, 1, 5) # 0부터 1까지 균등하게 5로 나눔

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() : 범위 내에서 균등 간격으로 로그 스케일 배열 생성

In [24]:
np.logspace(0.1 ,1 , 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성

- random.random() : 랜덤한 수의 배열 생성

In [25]:
np.random.random((3,3))

array([[0.4034559 , 0.38338399, 0.99589546],
       [0.88635035, 0.90025049, 0.10060598],
       [0.22636278, 0.42751529, 0.67121823]])

- random.randint() : 일정구간의 랜덤 정수의 배열 형성

In [26]:
np.random.randint(0, 10, (3,3))

array([[9, 4, 4],
       [1, 7, 6],
       [5, 4, 3]])

- random.normal() : 정규분포를 고려한 랜덤한 수의 배열생성

In [27]:
# 평균=0, 표준편차=1, 배열=3*3
np.random.normal(0, 1, (3,3))

array([[ 0.28020022,  0.55387313, -0.43961851],
       [ 0.11730818, -0.7780986 , -1.1979475 ],
       [-0.17715226,  0.36004204,  0.45824103]])

- random.rand(): 균등분포를 고려한 랜덤한 수의 배열 생성

In [28]:
np.random.rand(3,3)

array([[0.10316549, 0.2371618 , 0.18416824],
       [0.80786046, 0.83817439, 0.48481629],
       [0.68994596, 0.83831334, 0.869196  ]])

- random.randn() : 표준정규분포를 고려한 랜덤한 수의 배열 생성

In [29]:
np.random.randn(3,3)

array([[ 0.07495191,  1.49427608,  0.76882887],
       [-0.43017705, -0.32249472,  2.27121874],
       [-0.59813757, -2.27535706,  0.14064274]])

# 표준 데이터 타입

In [30]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
np.full((3,3), 1, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 배열 조회

In [33]:
def array_info(array) :
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:", array.size)
    print("itemsize:", array.itemsize)
    print("nbytes:" , array.nbytes)
    print("strides:" , array.strides)

In [34]:
print(array_info(a1))
print(array_info(a2))
print(array_info(a3))

[4 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20
strides: (4,)
None
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36
strides: (12, 4)
None
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int32
size: 27
itemsize: 4
nbytes: 108
strides: (36, 12, 4)
None


# 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 2 3 4 5]
4
3
5
4


In [36]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, -1])
print(a2[-2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
6
5


In [37]:
print(a3)
print(a3[0, 0, 0])
print(a3[2, 1, 2])
print(a3[-1, 2, 1])
print(a3[1, 0, -2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
6
8
2


# 슬라이싱(Slicing)

In [38]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 2 3 4 5]
[4 2]
[4 2 3 4 5]
[4]
[4 3 5]
[5 4 3 2 4]


In [39]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# 불리언 인덱싱(Boolean Indexing
- 배열 각 요소의 선택 여부를 True, False로 지정
- True 값인 인덱스만 조회

In [40]:
print(a1)
bool = [False, True, True, False, False]
print(a1[bool])

[4 2 3 4 5]
[2 3]


# 팬시 인덱싱(Fancy Indexing)

In [41]:
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])
idx = np.array([[0,1], [2,0]])
print(a1[idx])

[4 2 3 4 5]
[4, 3]
[4 3]
[[4 2]
 [3 4]]


In [42]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


### 배열 값 삽입
- insert() : 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [46]:
print(a1)

# a1의 0번째 인덱스에 10 삽입
b1 = np.insert(a1, 0, 10)
print(b1)
# c1의 2번째 인덱스에 10 삽입
c1 = np.insert(a1, 2, 10)
print(c1)

[4 2 3 4 5]
[10  4  2  3  4  5]
[ 4  2 10  3  4  5]


In [48]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정
- 배열의 인덱싱으로 접근하여 수정

In [55]:
print(a1)

# a1의 0번째 인덱스를 1로 수정
a1[0]=1
print(a1)
# a1의 n부터 n-1까지 0으로 수정
a1[:3]=0
print(a1)
# 팬시인덱싱을 사용해 a1의 1,3,4번째 인덱스를 1로 수정
i = np.array([1,3,4])
a1[i]=1
print(a1)
#팬시인덱싱을 사용해 a1의 1,3,4번째 인덱스에 +4
a1[i] += 4
print(a1)

[0 5 0 5 5]
[1 5 0 5 5]
[0 0 0 5 5]
[0 1 0 1 1]
[0 5 0 5 5]


### 배열 값 삭제
- delete() : 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [57]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[0 5 0 5 5]
[0 0 5 5]
[0 5 0 5 5]


In [59]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


### 배열복사
- copy() : 배열이나 하위배열 내의 값을 명시적으로 복사
- 원본 값 유지가능

In [61]:
print(a2)

a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 배열 전치 및 축 변경

In [57]:
print(a2)
print(a2.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


# 배열 재 구조화

- reshape() : 배열의 형상을 변경

In [63]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- newaxis(): 새로운 축 추가

In [65]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


# 배열 크기 변경
- 배열 모양만 변경

In [72]:
n2 = np.random.randint(0, 10, (2,5))
print(n2)

n2.resize((5,2))
print(n2)

[[5 7 0 9 1]
 [2 8 4 1 5]]
[[5 7]
 [0 9]
 [1 2]
 [8 4]
 [1 5]]


- 배열 크기 증가
- 남은 공간은 0으로 채움

In [73]:
n2.resize((5, 5))
print(n2)

[[5 7 0 9 1]
 [2 8 4 1 5]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


- 배열 크기 감소
- 포함되지 않은 값은 삭제

In [74]:
n2.resize((3,3))
print(n2)

[[5 7 0]
 [9 1 2]
 [8 4 1]]


### 배열 추가
- append() : 배열의 끝에 값 추가
- axis지정이 없으면 1차원 배열 형태로 변환되어 결합

In [76]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10, 19).reshape(3,3)
print(b2)

c2= np.append(a2, b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


- axis를 0으로 지정
- shape[0]을 제외한 나머지 shape은 같아야 함

In [79]:
c2 = np.append(a2, b2, axis=0)
c2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

- axis를 1으로 지정
- shape[1]을 제외한 나머지 shape은 같아야함

In [81]:
c2 = np.append(a2, b2, axis=1)
c2

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

### 배열 연결
- concatenate() : 튜플이나 배열의 리스트를 인수로 사용해 연결

In [83]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [85]:
# default값이 axis=0
a2 = np.array([[1,2,3], [4,5,6]])
np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [86]:
# axis=1
a2 = np.array([[1,2,3], [4,5,6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack() : 수직스택, 1차원으로 연결

In [87]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack() : 수평스택, 2차원 연결

In [88]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack() : 깊이스택, 3차원으로 연결

In [89]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack() : 새로운 차원으로 연결

In [90]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])