# 1. 학습목표

### 배열과 리스트의 차이점을 배워보자

In [2]:
import numpy as np

In [4]:
np.__version__

'1.19.2'

### 배열 자료구조 클래스인 ndarray-vector, matrix
### 배열의 차원과 크기 -ndim, shape

In [39]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {}, dimension : {}, dtype : {}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr )

### 1차원 배열 만들기

In [8]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


### Vectorized operation(백터화 연산)

In [16]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
answer = []
for d in data :
    answer.append(d * 2)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
data2 = [i*2 for i in data]
data2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
x = np.array(data)
x * 2
print(x, type(x))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### 비교연산, 논리연산

In [35]:
oneAry = np.array([1,2,3])
twoAry = np.array([10,20,30])

array([21, 42, 63])

In [36]:
oneAry + twoAry * 2

array([21, 42, 63])

In [38]:
oneAry == 2

array([False,  True, False])

In [41]:
twoAry > 10

array([False,  True,  True])

In [42]:
(oneAry == 2) & (twoAry > 10)

array([False,  True, False])

### 2차원 배열(행렬, matrix)

In [43]:
matrix = np.array([[0,1,2],[3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [45]:
print("행의갯수 : ", len(matrix))
print("행의갯수 : ", len(matrix[0]))

행의갯수 :  2
행의갯수 :  3


### 3차원 배열

In [50]:
threeDimAry = np.array([[[1,2,3,4,],
                         [5,6,7,8],
                         [9,10,11,12]],
                        [[11,12,13,14],
                         [15,16,17,18],
                         [19,20,21,22]]])

In [51]:
aryInfo(threeDimAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4), dimension : 3, dtype : int32
Array's Data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [54]:
print(len(threeDimAry), len(threeDimAry[0]), len(threeDimAry[0][0]))

2 3 4


In [56]:
x = np.array([100, 'hello', 3.14])
print('array {}'.format(x))
print('type {}'.format(type(x)))
print('x.type {}'.format(x.dtype))
print('x[0] type {}'.format(type(x[0])))

array ['100' 'hello' '3.14']
type <class 'numpy.ndarray'>
x.type <U11
x[0] type <class 'numpy.str_'>


In [57]:
data = np.array([0,1,2,3,4,5])
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (6,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5]


In [58]:
data[2]

2

In [59]:
data[-1]

5

In [60]:
matrix = np.array([[0,1,2],[3,4,5]])
aryInfo(matrix)

type : <class 'numpy.ndarray'>
shape : (2, 3), dimension : 2, dtype : int32
Array's Data : 
 [[0 1 2]
 [3 4 5]]


In [64]:
matrix[-1,-1]

5

In [69]:
# 슬라이싱
# 첫번째 행의 전체
print(matrix[0, :])
# 두번째 열의 전체
print(matrix[: , 1])
# 두번째 행의 두번째 열부터 끝까지
print(matrix[1, 1 : ])

[0 1 2]
[1 4]
[4 5]


In [76]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
aryInfo(m)

type : <class 'numpy.ndarray'>
shape : (3, 5), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [87]:
# 값 7을 인덱싱
print(m[1][2])
# 값 14를 인덱싱
print(m[-1][-1])
# 배열 [6,7] 슬라이싱
print(m[1,1:3])
# 배열 [7,12] 슬라이싱
print(m[1:,2])
# 배열 [[3,4], [8,9]] 슬리이싱
print(m[0:2, 3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [89]:
# boolian indexing
odd_even = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
aryInfo(odd_even)

type : <class 'numpy.ndarray'>
shape : (10,), dimension : 1, dtype : int32
Array's Data : 
 [0 1 2 3 4 5 6 7 8 9]


In [90]:
odd_even[idx]

array([0, 2, 4, 6, 8])

In [92]:
odd_even % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [93]:
odd_even[odd_even % 2 == 0]

array([0, 2, 4, 6, 8])

In [97]:
# fancing indexing
data = np.array([1,2,3,4,5,6,7,8,9])
idx  = np.array([0,2,4,6,8])
data[idx]

array([1, 3, 5, 7, 9])

In [99]:
idx = np.array([0,0,0,1,1,1,2,2,2])
data[idx]

array([1, 1, 1, 2, 2, 2, 3, 3])

In [100]:
n_dim_ary = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
aryInfo(n_dim_ary)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [101]:
n_dim_ary[ : , [0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [103]:
n_dim_ary[ : , [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [105]:
# 배열 순서 바꾸기
n_dim_ary[ [2,0,1], : ]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [106]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
aryInfo(x)

type : <class 'numpy.ndarray'>
shape : (20,), dimension : 1, dtype : int32
Array's Data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [115]:
# 3의배수
print(x[x % 3 == 0])
# 4로 나누어 남는 수가 1
print(x[x % 4 == 1])
# 3으로 나눠지고 4로 나누면 1이 남는 수
print(x[(x % 4 == 1) & (x % 3 == 0)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


### 배열의 생성과 변형

In [116]:
ary = np.arange(0, 12, 1)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (12,), dimension : 1, dtype : int32
Array's Data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [117]:
ary = np.arange(0, 12, 2)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (6,), dimension : 1, dtype : int32
Array's Data : 
 [ 0  2  4  6  8 10]


In [118]:
ary = np.arange(0, 12, 1).reshape(3,4)
aryInfo(ary)

type : <class 'numpy.ndarray'>
shape : (3, 4), dimension : 2, dtype : int32
Array's Data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [121]:
# 값 10
print(ary[2,2], type(ary[2,2]))
# 값 6
print(ary[])

10 <class 'numpy.int32'>
