### 실습을 통한 넘파이 개념 정리 및 구현 

In [1]:
import numpy as np

In [2]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {}, dimension : {}, dtype : {}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr )

### [실습 01] - ratings.dat

In [3]:
# userid, movieid, rating, timestamp
data = np.loadtxt('../data/ratings.dat' , delimiter = "::", dtype=np.int64)
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4), dimension : 2, dtype : int64
Array's Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [4]:
# 데이터의 첫 5 행만 확인
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [5]:
# 전체 평균 평점 계산
GPA = data[:, 2].mean()
GPA

3.581564453029317

In [34]:
# 사용자 아이디 수집
user_ids = np.unique(data[:, 0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [102]:
# 사용자 아이디별 평점 확인
user_ids_mean= []
for user_id in user_ids:
    user_data = data[data[ : , 0] == user_id, :]
    user_mean = user_data[ : , 2].mean()
    user_ids_mean.append([user_id, user_mean])
user_ids_mean

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

In [118]:
# 리스트를 Numpy 배열로 변환
movie_user_mean = np.array(mean_user_ids)

In [119]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
# 리스트는 Boolean Indexing이 안되므로, 배열로 변환해야 인덱싱, 슬라이싱을 할 수 있음
upper_04 = np.array([movie_user_mean[ : , 1:2]])
bool = upper_04[upper_04 > 4]
aryInfo(bool)

type : <class 'numpy.ndarray'>
shape : (1455,), dimension : 1, dtype : float64
Array's Data : 
 [4.18867925 4.19047619 4.32258065 ... 4.25       4.13461538 4.0952381 ]


In [ ]:
# 계산 결과를 csv 파일로 저장 : np.savetext('.xxxxcsv', xxxxx, delimiter=",")

### [실습 02] - seoul.csv, daegu.csv
- NumPy를 이용하여 다음의 내용을 구합니다. 
- 데이터에 결측치가 포함되어 있을 수 있습니다. 주의하세요!! 
- 중복된 내용이 있으면 모두 출력하며 오름차순으로 정렬하여 출력합니다.

In [226]:
# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
ary_seoul = np.loadtxt('../data/seoul.csv' , delimiter = ",", dtype=np.object, skiprows=1)
print(aryInfo(ary_seoul))
ary_daegu = np.loadtxt('../data/daegu.csv' , delimiter = ",", dtype=np.object, skiprows=1)
print(aryInfo(ary_daegu))

type : <class 'numpy.ndarray'>
shape : (40819, 5), dimension : 2, dtype : object
Array's Data : 
 [['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5']
 ['2020-09-05' '108' '23.3' '19.2' '27.3']
 ['2020-09-06' '108' '21.7' '19.5' '24.4']]
None
type : <class 'numpy.ndarray'>
shape : (41493, 5), dimension : 2, dtype : object
Array's Data : 
 [['1907-01-31' '143' '' '-7' '0.8']
 ['1907-02-01' '143' '' '' '']
 ['1907-02-02' '143' '' '' '']
 ...
 ['2020-09-04' '143' '24.1' '18.3' '30.4']
 ['2020-09-05' '143' '19.9' '17.3' '23.1']
 ['2020-09-06' '143' '19.5' '17.6' '20.7']]
None


In [229]:
# 1. 기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 언제였고, 몇도인가요?
ary_seoul_temp = ary_seoul.T[4]
print(ary_seoul_temp)
ary_seoul_temp.max()

['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']


'9.9'

In [ ]:
high_temp_arr = ary_seoul.T[4]
high_temp = (high_temp_arr[high_temp_arr != '']).astype(np.float64).max()
high_day = (ary_seoul.T[0][high_temp_arr == str(high_temp)])
print('서울의 최고 기온이 가장 높았던 날은 {}, {}.'.format(high_day,high_temp))

In [222]:
# 2. 역사적으로 일교차가 가장 큰 날짜는 몇년 몇월 몇일 인가요?
temp = np.array(ary_seoul[:, 4], dtype="f") - np.array(ary_seoul[:, 3], dtype="f")
temp

ValueError: could not convert string to float: ''

In [ ]:
dif = arr[:, 4].astype(np.float64)-arr[:, 3].astype(np.float64)
day = arr[dif.argmax(),0]
print('#2. 일교차가 가장 큰 날은 {}, 값은 {}'.format(day,dif.max()))

In [ ]:
# 3. 1년 중 평균적으로 일교차가 가장 큰 날짜는 몇월 몇일 인가요?

In [ ]:
# 4. 가장 덥다고 알려진 대구보다 서울이 더 더운날이 가장 많은 연도는 언제인가요?