### 실습을 통한 넘파이 개념 정리 및 구현 

In [11]:
import numpy as np

In [12]:
def aryInfo(arr) :
    print("type : {}".format(type(arr)))
    print("shape : {}, dimension : {}, dtype : {}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data : \n" , arr )

In [13]:
# userid, movieid, rating, timestamp
data = np.loadtxt('../data/ratings.dat' , delimiter = "::", dtype=np.int64)
aryInfo(data)

type : <class 'numpy.ndarray'>
shape : (1000209, 4), dimension : 2, dtype : int64
Array's Data : 
 [[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [14]:
# 데이터의 첫 5 행만 확인
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [15]:
# 전체 평균 평점 계산
GPA = data[:, 2].mean()
GPA

3.581564453029317

In [16]:
# 사용자 아이디 수집
data[:, :1]

array([[   1],
       [   1],
       [   1],
       ...,
       [6040],
       [6040],
       [6040]], dtype=int64)

In [ ]:
# 사용자 아이디별 평점 확인
mean_userids= []
for user_id in user_ids:
    data_for_user = data[user == data[ : , 0], :]
    user_mean = data_for_user[:,2].mean()
    mean_userids.append([user,user_mean])
mean_userids

In [ ]:
# 리스트를 Numpy 배열로 변환

In [ ]:
# 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기
# 리스트는 Boolean Indexing이 안되, 배열로 변환해야 인덱싱, 슬라이싱을 할 수 있음

In [ ]:
# 계산 결과를 csv 파일로 저장 : np.savetext('.xxxxcsv', xxxxx, delimiter=",")