In [7]:
import numpy as np
import pandas as pd

from tensorflow import keras
import tensorflow as tf
print(tf.__version__)
print(keras.__version__)

2.2.0
2.3.0-tf


### load data

In [8]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [9]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

In [10]:
for idx in range(10) :
    print(y_train[idx])

5
0
4
1
9
2
1
3
1
4


In [11]:
# 이진분류가 아니기 때문에 원핫 인코딩을 해야함
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [12]:
for idx in range(10) :
    print(y_train[idx])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 1차원으로 reshape
x_train = x_train.reshape(60000, 784)
x_test  = x_test.reshape(10000, 784)

In [14]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((60000, 784), (60000, 10), (10000, 784), (10000, 10))

### create model

In [15]:
model = keras.Sequential()
model.add(keras.layers.Dense(256, activation='sigmoid', input_shape=(784,) , name='input'))

model.add(keras.layers.Dense(128, activation='sigmoid', name='hidden1'))
model.add(keras.layers.Dense(64 , activation='sigmoid', name='hidden2'))
model.add(keras.layers.Dense(32 , activation='sigmoid', name='hidden3'))

model.add(keras.layers.Dense(10 , activation='softmax', name='output'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (Dense)                (None, 256)               200960    
_________________________________________________________________
hidden1 (Dense)              (None, 128)               32896     
_________________________________________________________________
hidden2 (Dense)              (None, 64)                8256      
_________________________________________________________________
hidden3 (Dense)              (None, 32)                2080      
_________________________________________________________________
output (Dense)               (None, 10)                330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________


### model compile

In [19]:
optimizer = keras.optimizers.SGD(learning_rate=0.01)
model.compile(optimizer = optimizer,
              loss      = 'categorical_crossentropy',
              metrics   = ['accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (Dense)                (None, 256)               200960    
_________________________________________________________________
hidden1 (Dense)              (None, 128)               32896     
_________________________________________________________________
hidden2 (Dense)              (None, 64)                8256      
_________________________________________________________________
hidden3 (Dense)              (None, 32)                2080      
_________________________________________________________________
output (Dense)               (None, 10)                330       
Total params: 244,522
Trainable params: 244,522
Non-trainable params: 0
_________________________________________________________________


### model fit

In [25]:
history = model.fit(x_train, y_train, batch_size=100, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
600/600 [==============================] - 2s 4ms/step - loss: 1.0930 - accuracy: 0.6982 - val_loss: 1.0666 - val_accuracy: 0.7036
Epoch 2/10
600/600 [==============================] - 3s 4ms/step - loss: 1.0255 - accuracy: 0.7221 - val_loss: 1.0027 - val_accuracy: 0.7415
Epoch 3/10
600/600 [==============================] - 3s 4ms/step - loss: 0.9636 - accuracy: 0.7529 - val_loss: 0.9417 - val_accuracy: 0.7704
Epoch 4/10
600/600 [==============================] - 3s 4ms/step - loss: 0.9037 - accuracy: 0.7794 - val_loss: 0.8823 - val_accuracy: 0.8049
Epoch 5/10
600/600 [==============================] - 3s 5ms/step - loss: 0.8454 - accuracy: 0.8063 - val_loss: 0.8262 - val_accuracy: 0.8239
Epoch 6/10
600/600 [==============================] - 3s 5ms/step - loss: 0.7894 - accuracy: 0.8255 - val_loss: 0.7688 - val_accuracy: 0.8424
Epoch 7/10
600/600 [==============================] - 2s 4ms/step - loss: 0.7342 - accuracy: 0.8454 - val_loss: 0.7154 - val_accuracy: 0.8527
Epoch 

In [26]:
history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

### 평가

In [27]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.5828 - accuracy: 0.8843


[0.5827834606170654, 0.8842999935150146]