In [1]:
import sklearn
sklearn.__version__

'0.23.2'

In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
keys = iris.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
# 지도학습의 정답
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

- feature dataset 확인

In [12]:
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

- 레이블(결정값, 타겟, 클래스)확인

In [13]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

- dataframe 변환

In [14]:
iris_df = pd.DataFrame(data = iris_data,
                       columns = iris.feature_names)

iris_df['target'] = iris_label

iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

- 학습데이터(training data : validation data)와 테스트 데이터(test data) 세트로 분리
- train_test_split(test_size, train_size, shuffle, random_size)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, shuffle=False, random_state=20)
print('train data  :\n', X_train)
print('train label :\n', X_test)
print('test data   :\n', y_train)
print('test label  :\n', y_train)

train data  :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.

- 알고리즘을 활용한 학습과 분류

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dt_clf = DecisionTreeClassifier(random_state = 20)
dt_clf

DecisionTreeClassifier(random_state=20)

In [18]:
# 학습(fit)
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=20)

- 예측은 학습데이터가 아닌 다른 데이터(test data)를 이용해야 한다.

In [19]:
prediction = dt_clf.predict(X_test)
print('predict\n', prediction)
print('y_test\n', y_test)

predict
 [2 1 2 2 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2]
y_test
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


- 예측 정확도 평가

In [20]:
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.2f}'.format(accuracy_score(y_test, prediction)))

예측 정확도 : 0.77


- 학습 데이터와 테스트 테이터를 분리 시키지 않았을 때

In [21]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

bad_iris = load_iris()

train_data = bad_iris.data
train_label = bad_iris.target

bad_dt_clf = DecisionTreeClassifier(random_state=20)
bad_dt_clf.fit(train_data, train_label)

pred = bad_dt_clf.predict(train_data)
print('예측 정확도 : {0:.2f}'.format(accuracy_score(train_label, pred)))

예측 정확도 : 1.00


### 교차검증(Cross validation)

- KFold 방식

In [22]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.model_selection import KFold

In [23]:
fold_iris = load_iris()
fold_iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [24]:
features = fold_iris.data
label = fold_iris.target

fold_df_clf = DecisionTreeClassifier()
fold_df_clf

DecisionTreeClassifier()

In [25]:
# 5개의 폴더세트를 분리하여 각 폴드 세트별 정확도를 담을 리스트 생성
cv_accuracy = []
kfold = KFold(n_splits = 5)

In [26]:
features.shape

(150, 4)

In [27]:
n_iter = 0

for train_idx, test_idx in kfold.split(features) :
    #print(len(train_idx), len(test_idx), train_idx, test_idx)
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
    
    # 학습 및 예측
    fold_df_clf.fit(X_train, y_train)
    pred = fold_df_clf.predict(X_val)
    n_iter += 1
    
    # 검증 정확도 측정
    acc = np.round(accuracy_score(y_val, pred), 4)
    print('{} 교차 검증 정확도 : {}, 학습 데이터 크기 : {}, 검증 데이터 크기 : {}'.format(n_iter, acc, X_train.shape[0], X_val.shape[0]))
    print('{} 검증 세트 인덱스 : {}'.format(n_iter, X_val.shape[0]))
    
    cv_accuracy.append(acc)
    
print(np.mean(cv_accuracy))

1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
1 검증 세트 인덱스 : 30
2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
2 검증 세트 인덱스 : 30
3 교차 검증 정확도 : 0.8333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
3 검증 세트 인덱스 : 30
4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
4 검증 세트 인덱스 : 30
5 교차 검증 정확도 : 0.8, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
5 검증 세트 인덱스 : 30
0.9066599999999999


- Stratified KFold : 불균형한 분포를 가진 데이터 집합에 적용하는 CV
- 기존 kfold는 레이블값의 분포를 반영하지 않기 때문에 상황에 따라 예측 정확도가 0일 수 있다.

In [28]:
fold_iris_df = pd.DataFrame(data = fold_iris.data, columns = fold_iris.feature_names)
fold_iris_df['target'] = fold_iris.target

fold_iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [29]:
fold_iris_df['target'].value_counts()

2    50
1    50
0    50
Name: target, dtype: int64

In [30]:
# 문제점 확인

kfold = KFold(n_splits=3)
n_iter = 0

for train_idx, test_idx in kfold.split(fold_iris_df) :
    label_train = fold_iris_df['target'].iloc[train_idx]
    label_val = fold_iris_df['target'].iloc[test_idx]
    n_iter += 1
    
    print('교차 검증{}'.format(n_iter))
    print('학습 레이블 데이터 분포\n', label_train.value_counts())
    print('검증 레이블 데이터 분포', label_val.value_counts())

교차 검증1
학습 레이블 데이터 분포
 2    50
1    50
Name: target, dtype: int64
검증 레이블 데이터 분포 0    50
Name: target, dtype: int64
교차 검증2
학습 레이블 데이터 분포
 2    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포 1    50
Name: target, dtype: int64
교차 검증3
학습 레이블 데이터 분포
 1    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포 2    50
Name: target, dtype: int64


In [31]:
# 문제점 해결
from sklearn.model_selection import StratifiedKFold

In [32]:
skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_idx, test_idx in skf.split(fold_iris_df, fold_iris_df['target']) :
    label_train = fold_iris_df['target'].iloc[train_idx]
    label_val = fold_iris_df['target'].iloc[test_idx]
    n_iter += 1
    
    print('교차 검증{}'.format(n_iter))
    print('학습 레이블 데이터 분포\n', label_train.value_counts())
    print('검증 레이블 데이터 분포\n', label_val.value_counts())

교차 검증1
학습 레이블 데이터 분포
 2    34
1    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 1    17
0    17
2    16
Name: target, dtype: int64
교차 검증2
학습 레이블 데이터 분포
 1    34
2    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 2    17
0    17
1    16
Name: target, dtype: int64
교차 검증3
학습 레이블 데이터 분포
 0    34
2    33
1    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 2    17
1    17
0    16
Name: target, dtype: int64


In [52]:
# 교차검증 정확도 확인

dt_clf = DecisionTreeClassifier(random_state = 100)
skf = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

for train_idx, test_idx in skf.split(features, label) :
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
    
    # 학습과 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_val)
    
    # 반복시 정확도 측정
    n_iter += 1
    print('{} 교차 검증 정확도 : {}, 학습 데이터 크기 : {}, 검증 데이터 크기 : {}'
          .format(n_iter, acc, X_train.shape[0], X_val.shape[0]))
    print('{} 검증 세트 인덱스 : {}'.format(n_iter, X_val.shape[0]))
    
    cv_accuracy.append(acc)


print('교차 검증 정확도', np.round(cv_accuracy, 4))
print('평균 검증 정확도', np.mean(cv_accuracy))

1 교차 검증 정확도 : 0.8, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
1 검증 세트 인덱스 : 50
2 교차 검증 정확도 : 0.8, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
2 검증 세트 인덱스 : 50
3 교차 검증 정확도 : 0.8, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
3 검증 세트 인덱스 : 50
교차 검증 정확도 [0.8 0.8 0.8]
평균 검증 정확도 0.8000000000000002
