<a href="https://colab.research.google.com/github/dhdmsdud/TIL/blob/master/MLP_regression_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.datasets   import boston_housing
from tensorflow.keras.models     import Sequential, Model
from tensorflow.keras.layers     import Activation, Dense
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.utils      import plot_model


from sklearn.model_selection     import train_test_split
from sklearn.preprocessing       import StandardScaler, MinMaxScaler


import numpy  as np
import pandas as pd


import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

57344/57026 [==============================] - 0s 0us/step


In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((404, 13), (404,), (102, 13), (102,))

In [ ]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [ ]:
y_train[0]

15.2

In [ ]:
model = Sequential()

model.add(Dense(10, input_shape=(13, )))
model.add(Activation('sigmoid'))

model.add(Dense(8, activation='sigmoid'))
model.add(Dense(6, activation='sigmoid'))
model.add(Dense(4, activation='sigmoid'))

model.add(Dense(1))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 28        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 315
Trainable params: 315
Non-trainable params: 0
________________________________________________________

In [ ]:
plot_model(model)

In [ ]:
model.compile(loss='mse', optimizer=Adam(learning_rate=0.02), metrics=['mse'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 28        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 315
Trainable params: 315
Non-trainable params: 0
________________________________________________________

In [ ]:
history = model.fit(X_train, y_train , batch_size = 50 , epochs = 100 , validation_data=(X_test, y_test), verbose = 1 )
#model.fit(X_train, y_train , batch_size = 50 , epochs = 100 , verbose = 1 )

In [ ]:
history.history.keys()

dict_keys(['loss', 'mse', 'val_loss', 'val_mse'])

In [ ]:
result = model.evaluate(X_test, y_test)
print('loss', result[0])
print('mse', result[1])

4/4 [==============================] - 0s 3ms/step - loss: 83.8151 - mse: 83.8151
loss 83.81512451171875
mse 83.81512451171875


### 성능개선을 위한 작업
- 스케일링
- 학습데이터를 학습, 검증으로 나눔
- 모델생성시 activation='relu', 컴파일 optimizer=SGD
- 학습, 결과 확인

In [ ]:
(X_train_raw, y_train_raw), (X_test, y_test) = boston_housing.load_data()

In [ ]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train_raw)

In [ ]:
X_train_scaler[0]

array([-0.27224633, -0.48361547, -0.43576161, -0.25683275, -0.1652266 ,
       -0.1764426 ,  0.81306188,  0.1166983 , -0.62624905, -0.59517003,
        1.14850044,  0.44807713,  0.8252202 ])

In [ ]:
scaler = StandardScaler()
X_test_scaler = scaler.fit_transform(X_test)

In [ ]:
X_test_scaler[0]

array([ 2.8040301 , -0.50784934,  0.96960877, -0.32969024,  1.23174581,
        0.11934137,  1.14739788, -0.91935276,  1.60609286,  1.40778227,
        0.90513041, -4.27829517,  2.51324773])

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X_train_scaler, y_train_raw)

In [ ]:
model = Sequential()

model.add(Dense(128, input_shape=(13, ), activation='relu'))

model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))

model.add(Dense(1))

In [ ]:
model.compile(loss='mse', optimizer=SGD(learning_rate=0.02), metrics=['mse'])

In [ ]:
model.fit(X_train, y_train , batch_size = 50 , epochs = 300 , validation_data=(X_val, y_val), verbose = 1 )

Epoch 1/300
7/7 [==============================] - 0s 27ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 2/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 3/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 4/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 5/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 6/300
7/7 [==============================] - 0s 8ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 7/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 8/300
7/7 [==============================] - 0s 7ms/step - loss: nan - mse: nan - val_loss: nan - val_mse: nan
Epoch 9/300
7/7 [==============================] - 0s 7ms/step 

In [ ]:
result = model.evaluate(X_test, y_test)
print('loss', result[0])
print('mse', result[1])

4/4 [==============================] - 0s 3ms/step - loss: nan - mse: nan
loss nan
mse nan
